# Perfil activo por defecto (desarrollo)
spring.profiles.active=dev

# Nombre de la aplicación
spring.application.name=primeraapi

# Puerto del servidor
server.port=8081

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# Logging
logging.level.com.dpi.primeraapi=DEBUG