# Configuración PRODUCCIÓN (Railway)
# Railway proveerá estas variables automáticamente
spring.datasource.url=${JAWSDB_URL}
spring.datasource.username=${JAWSDB_USERNAME}
spring.datasource.password=${JAWSDB_PASSWORD}

# Configuración optimizada para producción
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Puerto (Railway asigna uno automáticamente)
server.port=${PORT:8080}

# Perfil activo
spring.profiles.active=prod